# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Skynettechnologies\BoltAllinoneaccessibility\Field\AllinoneaccessibilityFieldType:
        tags: ['bolt.field']
            
    Skynettechnologies\BoltAllinoneaccessibility\TwigExtension:
        arguments:
            $params: '@parameter_bag'
        tags: ['twig.extension']

    Skynettechnologies\BoltAllinoneaccessibility\BoltAllinoneaccessibilityInjectorWidget: ~

    Skynettechnologies\BoltAllinoneaccessibility\Extension: ~

parameters:
    # Set your AIOA widget URL here
    aioa.widget_url: 'https://example.com/aioa.js'
